# Travis CI build and test file for ActivityLog2.  The aim is to check that
# the application builds correctly, and automated tests pass.  The build step
# runs build.rkt which also creates a distribution (in the past, creating a
# distribution has failed due to bad paths in `define-runtime-path`).
#
# Some of the automated tests depend on data that is downloaded from Google
# Drive, this is private data and it is encrypted.  It is downloaded by the
# `download-test-data.sh` script.

language: c
sudo: false

# Do not use caching of any kind, it is not really needed and possibly not a
# good idea when combined with the `download-test-data.sh`.  See also
# https://docs.travis-ci.com/user/caching/
#
cache: false

env:
  global:
    - RACKET_DIR=~/racket
    - DISPLAY=:99.0            # needed by the unit tests, see comment on xvfb

    # Print some useful warnings during complilation.  It would be good if
    # these would be made errors...

    - PLTSTDERR='error warning@optimizer'

    # This environment variable is only decrypted on builds that are from the
    # original repository.(this actually makes sense, if you think about it)
    # -- tests that depend on private data will only run on the official
    # branches.  See als https://docs.travis-ci.com/user/encryption-keys/.

    - secure: "UrtMaEd9RcXMSEaOK/0VJh7W5L1MIAIjcZnh38pHt/xDIRDCXhMNxkMCS6ra00UwrFaw1l3VcI5mNYWY1JP6Fct1LbU2AY+sKoNNkld5OigNUrx1eXhtzXy8a1T0gX0kJhWvPVAActRwnaWjmhUblH1UAOWOvfcX4laekAVXbSJOVCBKSQl7HNl0xJBm0TriAZtWg+pumTG93e2+3hza6cWQ0tJHqn1kwBmD6aKTJLpd05IU3g6bl/+4cOGosnOaD8L/fDjA51Hl5kwHXPxTrNkoLqRdrCfX+q5vF9D6qG6VdS4lxiNKDTCvnKQ8TZXsvF+WIvIaQSR8CrqqO5pfZWHQNkMJ6jIFrLrV77xx5fa4wWamOgeoZ2GhkXjlg/0qVTVU30h4qZbijbP7byyyErLKujklIYJPgRcgp8ok7pMs4qyqMK7lWyrwYQ7lc/e0PvS/stz8tGSVMboHsVFcP1IlQHAaQJK7Nlk3Pzxktx9CtOHOn/DW7Bw+eRd/zF24GqZKBwxB5VbgBWxpPfukWUwejo/uIevMGGSDnPOmNXvWeQL0LJ8C6qKUSfaH9+5YGwkev46MH41KyWfyekqjbASxNx3MU7SXeFrwT/5jQVENhD/zAUVMVk4Nr6YmAWm1iD66RvpJ/Y3lHn0roQ3CUVKWsHR/l5cNd8SYx5RT7nU="
  matrix:
    - RACKET_VERSION=7.5
    - RACKET_VERSION=HEADCS
matrix:
  allow_failures:
    - env: RACKET_VERSION=HEAD
    - env: RACKET_VERSION=HEADCS
    - env: RACKET_VERSION=RELEASE
  fast_finish: true
services:
  - xvfb
before_install:
  - bash ./etc/scripts/install-racket.sh
  - export PATH="${RACKET_DIR}/bin:${PATH}"
  - bash ./etc/scripts/setup-catalog.sh -i pkgs/
install:
  - raco pkg install --auto tzinfo tzgeolookup data-frame plot-container
before_script:
  # the X virtual frame buffer is needeed to run the tests, since they require
  # the GUI libraries which in turn try to connect to X even if no windows are
  # actually opened.  It takes a short while for the xvfb to start, but since
  # it is only needed after the build, we don't sleep here (the download test
  # data + build take about 6 minutes currently).
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16
  - bash ./etc/scripts/fetch.sh -d -C test "1ig99PhGTYFZsbOhJDph1za8gfG1GZCM_" # test-db(4)
  - bash ./etc/scripts/fetch.sh -d -C test "1AErlDi7m0GWlwjkAaNi2pHnK6u1dwdqZ" # test-fit(13)
script:
  - racket build.rkt
  - raco test test/fit2-test.rkt
  - raco test test/db-test.rkt
  - raco test test/db-upgrade-test.rkt
  # run trends before the aggregate test, as we want our
  # {BAVG,HIST,SCATTER}_CACHE tables to be empty.
  - raco test test/trends-test.rkt
  - raco test test/aggregate-test.rkt
  - raco test test/fit-test.rkt
after_success:
  # If the build succeded, check for unnecessary dependencies on files changed
  # in the last commit.  We should really check files that have changed since
  # the last build, but I don't know how to configure that.  Checking all the
  # files every time takes too long.
  #
  # We only check this if the build succeded (it is not an error to have
  # unnecessary requires), and the result has to be inspected in Travis to see
  # if anything needs to be done.  This is really a code quality metric.
  - bash ./etc/scripts/check-requires.sh -l 1
after_script:
