language: c
sudo: false
env:
  global:
  - RACKET_DIR=~/racket
  - secure: 3vqwMDeZJu/3MZCE5jyg2m6c7FtnGq236/dtG0ka7PR4ep4UEyqvzTyFw2G72iaZucTdhY0qq2WqgMTh54+vp+TW7dNCF9E5JCzcmKRPhn00ElpsghocPvniBlBW8KeBCqtbJGKaBTJrNtsAV48DlmZsNGTT6hvJliLPVeMB+mab7+0sStB+Bn2tjpStkux+lH6u0WfPXVg7BmPAAaUNjjjcFqdGVDv58fx+iAjy81n/IaAgCMfjQN9B7weSjTWiN8RzGthGusx0vCPupH4bzHoHzu6J/Vk2ExCT1y1KWV8faZR7PGTGmvWExDlp0s+fPOMocyop1uIIsJYqaGjZWjg1lSlXuzPB/lAxvmaqSYkRQSFuGQ4KUxvQRRNxt0OS96Eqho2dev6auCrE5BJ7HLT9hEAZ9AMrNpEA2gQ51a27lTMrYfrSiYl1W4L172Fd9eJL08sVeu27g3VNH/4wPUqbiQr76lIMRsjwcqPUwFL11UsA78eTzkj8B/1rW5YN4uTvC9ICVtgQYCJKlPbPv/CC22B/m6Vq5spYbtXgWV6mvIYO/oAx8114rK5eNtHcv5zBo6VM8xo5/x1CedIOwkHmec0VQ8PSVi8UhP9oxlhYBnTXUb/Jc4FegrU2goBQ21KeIExOx7Z4kGgvi7tP0lTwABF+0AzXIEvb9S4AAfY=
  matrix:
  - RACKET_VERSION=6.9
matrix:
  allow_failures:
  - env: RACKET_VERSION=HEAD
  - env: RACKET_VERSION=RELEASE
  fast_finish: true
before_install:
- git clone https://github.com/greghendershott/travis-racket.git
- cat travis-racket/install-racket.sh | bash
- export PATH="${RACKET_DIR}/bin:${PATH}"
install: 
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sh ./test/download-test-db.sh
script:
- raco make run.rkt rkt/main.rkt
- raco test test/db-test.rkt test/df-test.rkt
- raco test test/db-upgrade-test.rkt
after_script: 
